// packages/vue/src/components/elements/Group.vue
<script setup lang="ts">
import { Group, GroupObject, omitBy } from '@grafikjs/core';
import { useCollection } from './../../hooks';
import { onMounted, onUnmounted, provide } from 'vue';
import ShapeBase from './ShapeBase.vue';

const props = defineProps<Partial<GroupObject>>();
const {
	actions: { add, remove }
} = useCollection(null, (collection) => ({
	add: collection.add.bind(collection),
	remove: collection.remove.bind(collection)
}));
const group = new Group(
	omitBy(props, (value, key) => typeof value === 'undefined' || key === 'children')
);

onMounted(() => {
	add(group);
});
onUnmounted(() => {
	remove(group);
});

provide('collection', group);
</script>

<template>
	<ShapeBase tagName="g" :shape="group" :props="props">
		<slot />
	</ShapeBase>
</template>

<style scoped></style>

// packages/react/src/components/elements/group.tsx
import {
	useMemo,
	useEffect
} from 'react';
import {
	Group
} from '@grafikjs/core';

import {
	CollectionContext
} from './../../contexts';
import {
	useCollection
} from './../../hooks';
import {
	ShapeBase
} from './shape-base';

const ReactGroup = ({
	children,
	...props
}: any) => {

	const collection: any = useCollection();
	
	const group = useMemo(() => new Group(), []);

	useEffect(() => {

		collection.add(group);

		return () => {
			collection.remove(group);
		};

	}, []);

	return (
		<CollectionContext.Provider value={group}>
			<ShapeBase
				TagName='g'
				shape={group}
				props={props} >
				{children}
			</ShapeBase>
		</CollectionContext.Provider>
	);

};

export {
	ReactGroup as Group
};
