// packages/react/src/components/interactive/selector.tsx
import {
	useState,
	useEffect,
	useCallback
} from 'react';
import {
	useCanvas
} from './../../hooks'

const Selector = () => {

	const canvas: any = useCanvas();
	const selector = canvas.getSelector();
	const [style, setStyle] = useState(selector.getStyle());
	const onShapesSelecting = useCallback(() => {
		setStyle(selector.getStyle());
	}, []);

	useEffect(() => {

		canvas.on('selector:updated', onShapesSelecting);

		return () => {
			canvas.off('selector:updated', onShapesSelecting);
		};

	}, []);

	return (
		<div
			style={style}
			{...selector.getAttributes()} />
	);

};

export {
	Selector
};

// packages/vue/src/components/interactive/Selector.vue
<script setup>
import { ref, onMounted, onUnmounted } from 'vue';
import { useCanvas } from './../../hooks';

const canvas = useCanvas();
const attrs = ref(canvas.getSelector().getAttributes());
const style = ref(canvas.getSelector().getStyle());
const onSelect = () => {
	attrs.value = canvas.getSelector().getAttributes();
	style.value = canvas.getSelector().getStyle();
};

onMounted(() => {
	canvas.on('selector:updated', onSelect);
});

onUnmounted(() => {
	canvas.off('selector:updated', onSelect);
});
</script>

<template>
	<div v-bind="attrs" :style="style" />
</template>

<style scoped></style>
