// packages/vue/src/components/CanvasProvider.vue
<script setup lang="ts">
import { CanvasObject, Canvas } from '@grafikjs/core';
import { provide, watch } from 'vue';

const props = defineProps<{
	value: CanvasObject;
}>();
const canvas = new Canvas(props.value);
provide('canvas', canvas);

watch(props, (props) => {
	canvas.set(props.value);
});
</script>

<template>
	<slot />
</template>

<style scoped></style>

// packages/react/src/components/canvas-provider.tsx
import {
	useMemo
} from 'react';
import {
	Canvas
} from '@grafikjs/core';

import {
	CanvasContext
} from './../contexts';

const CanvasProvider = ({
	children,
	...props
}) => {

	const canvas = useMemo(() => new Canvas(props), []);

	return (
		<CanvasContext.Provider value={canvas}>
			{children}
		</CanvasContext.Provider>
	);

};

export {
	CanvasProvider
};
