// packages/vue/src/components/interactive/Control.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';
import ControlNode from './ControlNode.vue';
import { useCanvas } from './../../hooks';

const props = defineProps<{ control: any }>();
const canvas = useCanvas();
const nodes = props.control.getChildren();
const attrs = ref(props.control.getAttributes());
const style = ref(props.control.getStyle());
const onSet = () => {
	attrs.value = props.control.getAttributes();
	style.value = props.control.getStyle();
};

onMounted(() => {
	canvas.on('set', onSet);
	props.control.shape.on('set', onSet);
});

onUnmounted(() => {
	canvas.off('set', onSet);
	props.control.shape.off('set', onSet);
});
</script>

<template>
	<div v-bind="attrs" :style="style">
		<ControlNode v-for="node in nodes" :key="node.id" :node="node" />
	</div>
</template>

<style scoped></style>

// packages/react/src/components/interactive/control.tsx
import {
	useState,
	useEffect,
	useCallback
} from 'react';

import {
	ControlNode
} from './';

const Control = ({
	control
}: any) => {

	const TagName = control.get('tagName');
	const [attributes, setAttributes] = useState(control.getAttributes());
	const [style, setStyle] = useState(control.getStyle());
	const onShapeSet = useCallback(() => {
		setAttributes(control.getAttributes());
		setStyle(control.getStyle());
	}, []);

	useEffect(() => {

		control.shape.on('set', onShapeSet);
		control.shape.canvas.on('set', onShapeSet);

		return () => {
			control.shape.off('set', onShapeSet);
			control.shape.canvas.off('set', onShapeSet);
		};

	}, []);

	return (
		<TagName
			{...attributes}
			style={style} >
			{control.mapChildren(node => (
				<ControlNode
					key={node.id}
					node={node} />
			))}
		</TagName>
	);

};

export {
	Control
};
